services:
  server:
    build: ./server
    container_name: server
    env_file:
      - server/.env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  bot:
    build: ./bot
    container_name: bot
    depends_on:
      - server
    env_file:
      - bot/.env
    volumes:
      - ./bot:/app
